In [1]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,))

In [3]:
randint


tensor([  48, -100,  -52,   -3,   12,  -43])

In [4]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9,5.2]])

In [5]:
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [6]:
zeros = torch.zeros(2,3)

In [7]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
ones = torch.ones(3,4)

In [9]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
torch.empty(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [14]:

torch.linspace(5, 10 , steps = 3)

tensor([ 5.0000,  7.5000, 10.0000])

In [15]:

torch.logspace(5, 10 , steps = 3)

tensor([1.0000e+05, 3.1623e+07, 1.0000e+10])

In [16]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])