In [5]:
with open("wiz_of_oz.txt", 'r', encoding='utf-8') as f:
    content = f.read()

In [25]:
vocab_size = len(content)
vocab_size

233385

In [8]:
content[:200]

'\ufeffthe Wizard in Oz\n    \nThis ebook is for the use of anyone anywhere in the United States and\nmost other parts of the world at no cost and with almost no restrictions\nwhatsoever. You may copy it, give '

In [10]:
#Step1 - To create a vocabulary
chars = sorted(set(content))

In [11]:
chars

['\n',
 ' ',
 '!',
 '"',
 '#',
 '&',
 "'",
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '\ufeff']

In [12]:
len(chars)

83

In [21]:
string_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_string = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])


In [22]:

encoded_hello = encode('hello')

In [23]:
encoded_hello

[63, 60, 67, 67, 70]

In [24]:
decode(encoded_hello)

'hello'

In [32]:
%%time
encoded_contents = encode(content)

CPU times: total: 15.6 ms
Wall time: 22.1 ms


In [45]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

block_size = 8
batch_size = 4

cuda


In [35]:
%%time
data = torch.tensor(encode(content), dtype = torch.long)

CPU times: total: 0 ns
Wall time: 38.7 ms


In [31]:
data[:199]

tensor([82, 75, 63, 60,  1, 49, 64, 81, 56, 73, 59,  1, 64, 69,  1, 41, 81,  0,
         1,  1,  1,  1,  0, 46, 63, 64, 74,  1, 60, 57, 70, 70, 66,  1, 64, 74,
         1, 61, 70, 73,  1, 75, 63, 60,  1, 76, 74, 60,  1, 70, 61,  1, 56, 69,
        80, 70, 69, 60,  1, 56, 69, 80, 78, 63, 60, 73, 60,  1, 64, 69,  1, 75,
        63, 60,  1, 47, 69, 64, 75, 60, 59,  1, 45, 75, 56, 75, 60, 74,  1, 56,
        69, 59,  0, 68, 70, 74, 75,  1, 70, 75, 63, 60, 73,  1, 71, 56, 73, 75,
        74,  1, 70, 61,  1, 75, 63, 60,  1, 78, 70, 73, 67, 59,  1, 56, 75,  1,
        69, 70,  1, 58, 70, 74, 75,  1, 56, 69, 59,  1, 78, 64, 75, 63,  1, 56,
        67, 68, 70, 74, 75,  1, 69, 70,  1, 73, 60, 74, 75, 73, 64, 58, 75, 64,
        70, 69, 74,  0, 78, 63, 56, 75, 74, 70, 60, 77, 60, 73, 12,  1, 51, 70,
        76,  1, 68, 56, 80,  1, 58, 70, 71, 80,  1, 64, 75, 10,  1, 62, 64, 77,
        60])

In [37]:
#create train_test split(80/20)
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

In [43]:
n

186708

In [40]:

x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print('when your input is :',context, 'target is ', target)

when your input is : tensor([82]) target is  tensor(75)
when your input is : tensor([82, 75]) target is  tensor(63)
when your input is : tensor([82, 75, 63]) target is  tensor(60)
when your input is : tensor([82, 75, 63, 60]) target is  tensor(1)
when your input is : tensor([82, 75, 63, 60,  1]) target is  tensor(49)
when your input is : tensor([82, 75, 63, 60,  1, 49]) target is  tensor(64)
when your input is : tensor([82, 75, 63, 60,  1, 49, 64]) target is  tensor(81)
when your input is : tensor([82, 75, 63, 60,  1, 49, 64, 81]) target is  tensor(56)


In [41]:
x

tensor([82, 75, 63, 60,  1, 49, 64, 81])

In [42]:
y

tensor([75, 63, 60,  1, 49, 64, 81, 56])