In [1]:
!where python 

C:\Users\pytho\OneDrive\Documents\My Files\Dev Projects\llm_notes\myenv\Scripts\python.exe
C:\Users\pytho\anaconda3\python.exe
C:\Users\pytho\AppData\Local\Microsoft\WindowsApps\python.exe


In [2]:
from tiktoken import encoding_for_model

In [3]:
enc = encoding_for_model("text-davinci-003")
toks = enc.encode("They are splashing") #encode


In [4]:
toks

[2990, 389, 4328, 2140]

In [5]:
enc.decode_single_token_bytes(2990)

b'They'

In [7]:
from openai import ChatCompletion,Completion


In [8]:
aussie_sys = "You are an Aussie LLM that uses Aussie slang and analogies whenever possible."


In [13]:
import os
from openai import OpenAI

client = OpenAI(
    # This is the default and can be omitted
    api_key='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',
)

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Say this is a test",
        }
    ],
    model="gpt-3.5-turbo",
)


C:\Users\pytho\anaconda3\lib\genericpath.py:77: RuntimeWarning: coroutine 'main' was never awaited
  m = tuple(map(os.fspath, m))


RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

In [1]:
from transformers import AutoModelForCausalLM,AutoTokenizer
import torch

C:\Users\pytho\OneDrive\Documents\My Files\Dev Projects\llm_notes\myenv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
mn = "meta-llama/Llama-2-7b-hf"


In [10]:
from huggingface_hub import login
login('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')

Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to C:\Users\pytho\.cache\huggingface\token
Login successful


In [13]:
model = AutoModelForCausalLM.from_pretrained(mn, device_map=0, load_in_8bit=True, token='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')


OSError: You are trying to access a gated repo.
Make sure to request access at https://huggingface.co/meta-llama/Llama-2-7b-hf and pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`.

In [3]:
model = AutoModelForCausalLM.from_pretrained("TheBloke/Llama-2-7B-Chat-GPTQ",device_map='cuda')

In [15]:
tokenizer = AutoTokenizer.from_pretrained("TheBloke/Llama-2-7B-Chat-GPTQ")


tokenizer_config.json: 100%|███████████████████████████████████████████████████████████| 727/727 [00:00<00:00, 242kB/s]
tokenizer.model: 100%|██████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 1.69MB/s]
tokenizer.json: 100%|█████████████████████████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 1.96MB/s]
special_tokens_map.json: 100%|█████████████████████████████████████████████████████████| 411/411 [00:00<00:00, 137kB/s]


In [4]:
model

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 4096, padding_idx=0)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (rotary_emb): LlamaRotaryEmbedding()
          (k_proj): QuantLinear()
          (o_proj): QuantLinear()
          (q_proj): QuantLinear()
          (v_proj): QuantLinear()
        )
        (mlp): LlamaMLP(
          (act_fn): SiLU()
          (down_proj): QuantLinear()
          (gate_proj): QuantLinear()
          (up_proj): QuantLinear()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): LlamaRMSNorm()
  )
  (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
)

In [4]:
prompt = "Jeremy Howard is a "
toks = tokenizer(prompt, return_tensors="pt")



In [17]:
toks

{'input_ids': tensor([[    1,  5677,  6764, 17430,   338,   263, 29871]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}

In [19]:
tokenizer.batch_decode(toks['input_ids'])


['<s> Jeremy Howard is a ']

In [20]:
res = model.generate(**toks.to("cuda"), max_new_tokens=15).to('cpu')
res

C:\Users\pytho\OneDrive\Documents\My Files\Dev Projects\llm_notes\myenv\lib\site-packages\transformers\generation\utils.py:1518: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use and modify the model generation configuration (see https://huggingface.co/docs/transformers/generation_strategies#default-text-generation-configuration )
  warnings.warn(


tensor([[    1,  5677,  6764, 17430,   338,   263, 29871, 29941, 29945, 29899,
          6360, 29899,  1025,   767,   515,   278,  3303,  3900,  1058,   471,
         24383,   297]])

In [21]:
tokenizer.batch_decode(res)


['<s> Jeremy Howard is a 35-year-old man from the United States who was arrested in']

In [23]:
res = model.generate(**toks.to("cuda"), max_new_tokens=50).to('cpu')
res

tensor([[    1,  5677,  6764, 17430,   338,   263, 29871, 29941, 29945, 29899,
          6360, 29899,  1025,   767,   515,   278,  3303,  3900,  1058,   471,
         24383,   297,   498, 26517,   363, 16831, 23244, 15661,   304,  1560,
           688,  6234, 29871, 29896, 29889, 29941,  4679,   468, 25402,   310,
         10901, 11195,   286,   621,   314,   561,   300,   314,   457,   964,
           278,  4234, 29889,    13,  7504,  3278,   304]])

In [24]:
tokenizer.batch_decode(res)


['<s> Jeremy Howard is a 35-year-old man from the United States who was arrested in Thailand for allegedly attempting to smuggle 1.3 kilograms of crystal methamphetamine into the country.\nAccording to']

In [27]:
%%time
res = model.generate(**toks.to("cuda"), max_new_tokens=250).to('cpu')
res

CPU times: total: 11.5 s
Wall time: 18.8 s


tensor([[    1,  5677,  6764, 17430,   338,   263, 29871, 29941, 29945, 29899,
          6360, 29899,  1025,   767,   515,   278,  3303,  3900,  1058,   471,
         24383,   297,   498, 26517,   363, 16831, 23244, 15661,   304,  1560,
           688,  6234, 29871, 29896, 29889, 29941,  4679,   468, 25402,   310,
         10901, 11195,   286,   621,   314,   561,   300,   314,   457,   964,
           278,  4234, 29889,    13,  7504,  3278,   304,   263,  3461,   491,
           278, 14320, 29895,   554,  4918, 29892, 17430,   471, 24383,   472,
          2166,  1707,  7183, 29882, 15547, 18117,   297, 14320, 29895,   554,
          1156,  2888, 29879, 24921, 10943,   278, 15721,  7934,   297,   263,
          3577,   310, 11966,  1199,   540,   471, 19436, 29889,    13,  5328,
           538,  8967,   368, 20186,   304, 15661,   304,  1560,   688,  6234,
           278, 15721,   964,   498, 26517, 29892,   322,   540,   756,  1063,
         20139,   411, 15721,  1020,   600,   860,  

In [28]:
tokenizer.batch_decode(res)


["<s> Jeremy Howard is a 35-year-old man from the United States who was arrested in Thailand for allegedly attempting to smuggle 1.3 kilograms of crystal methamphetamine into the country.\nAccording to a report by the Bangkok Post, Howard was arrested at Suvarnabhumi Airport in Bangkok after customs officials discovered the drug hidden in a package of electronics he was carrying.\nHoward reportedly admitted to attempting to smuggle the drug into Thailand, and he has been charged with drug trafficking. If convicted, he could face up to 15 years in prison.\nIt is not uncommon for foreigners to be arrested in Thailand for drug-related offenses, as the country has strict laws and penalties for drug trafficking. However, in this case, Howard's arrest may have been facilitated by his use of a local airline to transport the drug.\nThai Airways International, the national carrier of Thailand, has a strict policy of not allowing passengers to carry any prohibited items, including drugs, on thei

In [2]:
model = AutoModelForCausalLM.from_pretrained("TheBloke/Llama-2-7B-Chat-GPTQ",device_map='cuda',torch_dtype=torch.float16)

In [3]:
tokenizer = AutoTokenizer.from_pretrained("TheBloke/Llama-2-7B-Chat-GPTQ")


In [5]:
%%time
res = model.generate(**toks.to("cuda"), max_new_tokens=250).to('cpu')
res

C:\Users\pytho\OneDrive\Documents\My Files\Dev Projects\llm_notes\myenv\lib\site-packages\transformers\generation\utils.py:1518: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use and modify the model generation configuration (see https://huggingface.co/docs/transformers/generation_strategies#default-text-generation-configuration )
  warnings.warn(


CPU times: total: 7.94 s
Wall time: 23 s


tensor([[    1,  5677,  6764, 17430,   338,   263, 29871, 29941, 29945, 29899,
          6360, 29899,  1025,   767,   515,   278,  3303,  3900,  1058,   471,
         24383,   297,   498, 26517,   363, 16831, 23244, 15661,   304,  1560,
           688,  6234, 29871, 29896, 29889, 29941,  4679,   468, 25402,   310,
         10901, 11195,   286,   621,   314,   561,   300,   314,   457,   964,
           278,  4234, 29889,    13,  7504,  3278,   304,   263,  3461,   491,
           278, 14320, 29895,   554,  4918, 29892, 17430,   471, 24383,   472,
          2166,  1707,  7183, 29882, 15547, 18117,   297, 14320, 29895,   554,
          1156,  2888, 29879, 24921, 10943,   278, 15721,  7934,   297,   263,
          3577,   310,  1304, 11966,  1199,   540,   471, 15661,   304,  7751,
          1250,   304,   278,  3148, 29889,    13,  5328,   538,  8967,   368,
         20186,   304,   278, 17268,   322,   471, 20139,   411, 15721,  1020,
           600,   860,   292, 29889,   960,  7602, 1

In [6]:
tokenizer.batch_decode(res)


['<s> Jeremy Howard is a 35-year-old man from the United States who was arrested in Thailand for allegedly attempting to smuggle 1.3 kilograms of crystal methamphetamine into the country.\nAccording to a report by the Bangkok Post, Howard was arrested at Suvarnabhumi Airport in Bangkok after customs officials discovered the drug hidden in a package of used electronics he was attempting to ship back to the US.\nHoward reportedly admitted to the crime and was charged with drug trafficking. If convicted, he could face up to 15 years in prison and a fine of up to 100,000 baht (approximately $3,200).\nThe arrest is the latest in a series of drug-related incidents involving foreigners in Thailand. In recent years, there have been several high-profile cases of foreigners arrested for drug offenses in the country.\nIt is important to note that drug laws in Thailand are strict and enforced strictly, and foreigners are not exempt from prosecution. If you are arrested or charged with a crime in T

In [8]:
model = AutoModelForCausalLM.from_pretrained('TheBloke/OpenOrca-Platypus2-13B-GPTQ',device_map='cuda',torch_dtype=torch.float16)


config.json: 100%|█████████████████████████████████████████████████████████████████████| 900/900 [00:00<00:00, 300kB/s]
C:\Users\pytho\OneDrive\Documents\My Files\Dev Projects\llm_notes\myenv\lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\pytho\.cache\huggingface\hub\models--TheBloke--OpenOrca-Platypus2-13B-GPTQ. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-star

OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB. GPU 0 has a total capacty of 6.00 GiB of which 0 bytes is free. Of the allocated memory 5.04 GiB is allocated by PyTorch, and 275.10 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF